# This is a basic workflow that is manually triggered

name: get latest jobs

on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: curl the latest jobs
      run: curl https://www.tesla.com/cua-api/apps/careers/state > jobs.json
